pybo/models.py
from flask_project.pybo import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String, primary_key=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set'))
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_project import config
# from flask_project.pybo import models #이 위치에 있으면 에러발생


db = SQLAlchemy()
migrate = Migrate()



def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from flask_project.pybo import models

    # blue print
    from .views import main_views, question_views, answer_views

    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)

    return app

pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from flask_project.pybo import db
from flask_project.pybo.models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    question = Question.query.get_or_404(question_id)
    content = request.form['content'] #html 상에서 textarea에 설정한 name='content'
    print(request.args.get('content'), request.args.to_dict())
    answer = Answer(content=content, create_date=datetime.now())
    question.answer_set.append(answer)
    db.session.commit()
    return redirect(url_for('_Question.detail', question_id=question_id))

pybo/views/main_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect

# main = Blueprint 별칭, __name__ = 모듈명인 main_views
bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/bp')
def ding():
    return redirect(url_for('_Question._list'))

@bp.route('/')
def index():
    return render_template('main/index.html')

pybo/views/question_views.py
from flask import Blueprint, render_template
from flask_project.pybo.models import Question

# _Question = Blueprint 별칭 또는 함수명, url 연결 함수명
bp = Blueprint('_Question', __name__, url_prefix='/question')

@bp.route('/list')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)

# @bp.route('/detail/<int:question_id>/')
@bp.route('/detail/<question_id>/')
def detail(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question)

pybo/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome flask exercise</title>
</head>
<body>
  <h1>DO it flask</h1>
  <li><a href="question/list">Click to go question</a></li>
  <li><a href="/bp"> click to go bp and redirect to question</a></li>

</body>
</html>

pybo/templates/question/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>내가 간다</title>
</head>
<body>
      {% if question %}
        <h1>질문 : {{ question.subject }}</h1>
        <ul>
            <li>{{question}}</li>
            <li>{{ question.id }}</li>
            <li>질문:{{ question.content }}</li>
            <li>질문일:{{ question.create_date}}</li>
        </ul>

        <h2>{{question.answer_set|length}} 개의 기등록된 답변</h2>
        <ul>
            {% for answer in question.answer_set %}
            <li>{{ answer.content }}</li>
    {% endfor %}
        </ul>

        <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post">
        <textarea name="content" id="content" rows="15"></textarea>
        <input type="submit" value="답변등록">
        </form>
    {% else %}
      <p>해당 질문에 대한 데이터를 찾을 수 없습니다.</p>
    {% endif %}





</body>
</html>

pybo/templates/question/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if question_list %}
        <ul>
        {% for question in question_list %}
<!--            <li><a href="/question/detail/{{ question.id }}/">{{ question.subject }}</a></li>-->


            <!--   _Question = Blueprint에서 지정한 별칭, detail = 선언했던 함수, question_id = 함수의 매개변수, question.id=html상으로 받은 데이터-->
            <li><a href="{{url_for('_Question.detail', question_id= question.id)}}">{{ question.subject }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>질문이 없습니다.</p>
    {% endif %}다
</body>
</html>